server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true #以ip注册到注册中心
spring:
  application:
    name: SPRING-CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ugly-kai/aigou-config.git
          username: 228441046@qq.com
          password: ZHANGKAIYUN251521

